const students = [ 
{name: 'Mikayla Alden', friends: ['Morgan Kjellesvig', 'Tristen Mina']},
{name: 'Sherine Aldrin', friends: ['Tayah Cazanjian']},
{name: 'Aaron Au', friends: ['Josh Lin']},
{name: 'Phoebe Awender', friends: []},
{name: 'Stephanie Bae', friends: ['Ian Stick']},
{name: 'Tylek Barnett', friends: []},
{name: 'Zach Bartell', friends: ['Alyssa Hunt']},
{name: 'Keila Barton', friends: []},
{name: 'Alex Beheshti', friends: []},
{name: 'Kristen Black', friends: ['Noah Matteson', 'Dylan Kinaan', 'Julianna Galang']},
{name: 'Alex Boch', friends: []},
{name: 'Emma Boykova', friends: ['Mason Minami']},
{name: 'Jocylin Braun', friends: []},
{name: 'Nathan Briones', friends: ['Andrew Leal']},
{name: 'Rachel Bruechert', friends: ['Gaurika Khillan']},
{name: 'Sydney Bruno', friends: ['Melody Hsu']},
{name: 'Bella Camacho', friends: ['Tayah Cazanjian', 'Sherine Aldrin']},
{name: 'Will Castro', friends: ['Rishab Nair', 'Sam Zia']},
{name: 'Tayah Cazanjian', friends: ['Luke Mills', 'Rachel Bruechert', 'Sherine Aldrin']},
{name: 'Dustin Chan', friends: []},
{name: 'May Chan', friends: []},
{name: 'Abigail Chang', friends: ['Brandon Yu', 'Alyssa Snider', 'Charlize Nishitoyo']},
{name: 'Brian Chang', friends: ['Kayden Stern']},
{name: 'Michelle Chen', friends: []},
{name: 'Sabrina Chen', friends: ['Skylar Qian']},
{name: 'Johanna Cheng', friends: ['Alex Zorzella', 'Jewel Han']},
{name: 'Devan Choksi', friends: ['Charles Yang']},
{name: 'Derek Chui', friends: []},
{name: 'Nolan Cook', friends: ['Caleb Klayko']},
{name: 'Elishah Davis', friends: []},
{name: 'Juliane Drake', friends: ['Lynn Sonu', 'Noah Hite']},
{name: 'Jackie Dugan', friends: []},
{name: 'Sarah Engelkemier', friends: ['Kennedy Shanafelt', 'Gaurika Khillan', 'Luke Mills']},
{name: 'Zach Fischer', friends: ['Mason Minami', 'York Li', 'Stephan Norquist', 'Ian Stick', 'Jack LeGue', 'Stephanie Bae']},
{name: 'Kelly Fiske', friends: ['Sam Zia', 'Rishab Nair']},
{name: 'Matthieu Foucu', friends: []},
{name: 'Isaac Fournier', friends: []},
{name: 'Lina Fujii', friends: ['Jocylin Braun']},
{name: 'Julianna Galang', friends: ['Nathan Richey']},
{name: 'Neel Gandhi', friends: ['Alex Beheshti']},
{name: 'Christian Gasca', friends: ['Marcus Vargas']},
{name: 'Yuna Ham', friends: []},
{name: 'Daphne Han', friends: []},
{name: 'Jewel Han', friends: ['Sydney Bruno']},
{name: 'Will Hartley', friends: ['Aaron Au', 'Josh Lin', 'Jon Taylor']},
{name: 'Kathryn Hewitt', friends: ['Lynn Sonu', 'Will Castro']},
{name: 'Caitlin Higuchi', friends: []},
{name: 'Noah Hite', friends: ['Lynn Sonu', 'Abigail Chang']},
{name: 'Danika Hsu', friends: ['Brandon Yu', 'Allyson Ting']},
{name: 'Melody Hsu', friends: []},
{name: 'Alyssa Hunt', friends: ['Dylan Kinaan', 'Zach Bartell']},
{name: 'Sophia Johnson', friends: []},
{name: 'Evan Kelly', friends: []},
{name: 'Gaurika Khillan', friends: ['Jewel Han', 'Maya Waugh']},
{name: 'Harrison Kim', friends: []},
{name: 'Isaac Kim', friends: []},
{name: 'Dylan Kinaan', friends: ['Alyssa Snider', 'Mason Minami', 'Kristen Black']},
{name: 'Morgan Kjellesvig', friends: ['Tristen Mina']},
{name: 'Caleb Klayko', friends: []},
{name: 'Minho Kwon', friends: []},
{name: 'Lydia Larson', friends: []},
{name: 'Daniel Lau', friends: []},
{name: 'Jerome Lau', friends: ['Andrew Leal']},
{name: 'Jon Le', friends: []},
{name: 'Andrew Leal', friends: ['Jerome Lau', 'Pat Vasavakul']},
{name: 'Aiden Lee', friends: ['Jon Thong', 'Josh Thong']},
{name: 'Jack LeGue', friends: ['Jon Lester', 'Noah Matteson']},
{name: 'Jon Lester', friends: []},
{name: 'York Li', friends: ['Maya Waugh', 'Zach Fischer', 'Ian Stick']},
{name: 'Brendan Lin', friends: []},
{name: 'Grace Lin', friends: []},
{name: 'Josh Lin', friends: ['Aaron Au', 'Jon Taylor', 'Mason Minami']},
{name: 'Kristin Lin', friends: ['Allyson Ting']},
{name: 'Tommy Lin', friends: []},
{name: 'Christopher Ling', friends: []},
{name: 'Abe Liu', friends: []},
{name: 'Jodi Liu', friends: []},
{name: 'Kirk Liu', friends: []},
{name: 'Noah Matteson', friends: []},
{name: 'Jaalen Mhoon', friends: []},
{name: 'Luke Mills', friends: []},
{name: 'Tristen Mina', friends: ['Morgan Kjellesvig']},
{name: 'Mason Minami', friends: ['Zach Fischer']},
{name: 'Nathey Mochizuki', friends: []},
{name: 'Ken Mori', friends: []},
{name: 'Seth Morris', friends: []},
{name: 'Kruthika Muddu', friends: []},
{name: 'Rishab Nair', friends: []},
{name: 'Serena Nam', friends: ['Abigail Chang']},
{name: 'Mike Nguyen', friends: []},
{name: 'Terry Nguyen', friends: []},
{name: 'Sarah Niemela', friends: []},
{name: 'Abby Ninan', friends: []},
{name: 'Charlize Nishitoyo', friends: ['Noah Hite']},
{name: 'Stephan Norquist', friends: ['Zach Fischer', 'Jane Oshatz']},
{name: 'Eric Oh', friends: []},
{name: 'Jillian Olson', friends: []},
{name: 'Jane Oshatz', friends: []},
{name: 'Julianna Owyang', friends: []},
{name: 'Victoria Pan', friends: []},
{name: 'Jayden Park', friends: []},
{name: 'Kiyomi Petersen', friends: ['Jon Le']},
{name: 'Ava Plata', friends: []},
{name: 'Trevor Polk', friends: []},
{name: 'Skylar Qian', friends: []},
{name: 'Taryn Riachy', friends: []},
{name: 'Nathan Richey', friends: ['Neel Gandhi', 'Nathan Briones']},
{name: 'Bethanie Rosales', friends: ['Zach Bartell', 'Dylan Kinaan']},
{name: 'Hana Rust', friends: []},
{name: 'William Sartorio', friends: []},
{name: 'Kennedy Shanafelt', friends: []},
{name: 'Nikita Sharma', friends: ['Sophie Xie', 'Kayden Stern']},
{name: 'Carissa Shiu', friends: []},
{name: 'Alyssa Snider', friends: ['Dylan Kinaan']},
{name: 'Maggie Sonne', friends: ['Cayden Tan']},
{name: 'Lynn Sonu', friends: []},
{name: 'Kayden Stern', friends: ['Sophie Xie']},
{name: 'Ian Stick', friends: []},
{name: 'Atul Surya', friends: []},
{name: 'Cayden Tan', friends: []},
{name: 'Ava Taylor', friends: ['Hana Rust', 'Zoe Wu', 'Allyson Ting']},
{name: 'Diamond Taylor', friends: []},
{name: 'Jon Taylor', friends: []},
{name: 'Angelin Tharp', friends: ['Jon Thong', 'Josh Thong', 'Kayden Stern']},
{name: 'Jon Thong', friends: ['Tommy Lin']},
{name: 'Josh Thong', friends: ['Tommy Lin']},
{name: 'Justus Tieche', friends: []},
{name: 'Allyson Ting', friends: ['Ava Taylor']},
{name: 'Jasmine Traidman', friends: []},
{name: 'Candace Tsay', friends: []},
{name: 'Jeremy Turner', friends: ['Sam Zia']},
{name: 'Marcus Vargas', friends: []},
{name: 'Pat Vasavakul', friends: ['Kiyomi Petersen']},
{name: 'Etienne Vezian', friends: ['Aiden Lee']},
{name: 'Anjali Vieira', friends: []},
{name: 'Shrivaas Vijayan', friends: []},
{name: 'Lucy Wang', friends: []},
{name: 'Nina Wang', friends: ['Stephanie Bae', 'Ian Stick']},
{name: 'Maya Waugh', friends: ['Ian Stick', 'Stephanie Bae', 'York Li', 'Isabella Zailer']},
{name: 'Miles Waugh', friends: ['Devan Choksi']},
{name: 'Sydnee Wei', friends: []},
{name: 'Elijah Wong', friends: []},
{name: 'Zoe Wu', friends: []},
{name: 'Sophie Xie', friends: ['Nikita Sharma', 'Jasmine Traidman', 'Kayden Stern']},
{name: 'Junze Xu', friends: []},
{name: 'Nathan Yan', friends: []},
{name: 'Charles Yang', friends: []},
{name: 'Benjamin Yi', friends: []},
{name: 'Brandon Yu', friends: []},
{name: 'Isabella Zailer', friends: ['Jillian Olson']},
{name: 'Eric Zhang', friends: []},
{name: 'Anne Zhou', friends: []},
{name: 'Sam Zia', friends: ['Will Castro']},
{name: 'Alex Zorzella', friends: ['Danika Hsu', 'Maya Waugh']},
]